import argparse
import sys
from datetime import datetime, timezone
from trainmate.db import db
from trainmate.google_sheets import sheets_reader
from trainmate.google_calendar import calendar_syncer
from trainmate.coach import coach_engine
from trainmate.config import config

def main():
    parser = argparse.ArgumentParser(
        description="TrainMate - Local Training Coach CLI",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Commands:
  status         Show current athlete status, active goals, recent metrics, and coach memories.
  plan           Generate or adapt the 4-week periodized training plan (saves locally).
  adapt          Run the daily Garmin check for today (syncs adapted workouts to Calendar).
  sync           Commit all local planned workouts to Google Calendar.
  sync-sheets    Fetch latest activities and daily metrics from Google Sheets.
  add-goal       Add a new training objective/goal.
  add-event      Add a new major life event (vacation, injury, party).
  list-goals     Show all training objectives.
  list-events    Show all logged life events.
  list-workouts  Show all planned workouts.
"""
    )
    parser.add_argument("command", nargs="?", help="Command to execute")
    args, command_args = parser.parse_known_args()

    if not args.command:
        parser.print_help()
        sys.exit(1)

    cmd = args.command.lower()
    
    if cmd == "status":
        run_status()
    elif cmd == "plan":
        run_plan()
    elif cmd == "adapt":
        run_adapt(command_args)
    elif cmd == "sync":
        run_sync()
    elif cmd == "sync-sheets":
        run_sync_sheets()
    elif cmd == "add-goal":
        run_add_goal(command_args)
    elif cmd == "add-event":
        run_add_event(command_args)
    elif cmd == "list-goals":
        run_list_goals()
    elif cmd == "list-events":
        run_list_events()
    elif cmd == "list-workouts":
        run_list_workouts()
    else:
        print(f"Unknown command: '{cmd}'")
        parser.print_help()
        sys.exit(1)

def run_status():
    print("=== TRAINMATE ATHLETE STATUS ===")
    
    # Active Goal
    objectives = db.get_objectives(status='active')
    if objectives:
        objectives.sort(key=lambda x: x['target_date'])
        next_goal = objectives[0]
        print(f"\nNext Objective: {next_goal['title']} ({next_goal['sport_type'].upper()})")
        print(f"Target Date   : {next_goal['target_date']}")
        print(f"Description   : {next_goal.get('description', '')}")
    else:
        print("\nNext Objective: None (TrainMate needs at least one goal to start planning)")

    # Recent Garmin metrics
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    metrics = db.get_metrics_cache()
    if metrics:
        last_metrics = metrics[-1]
        print(f"\nRecent Garmin Metrics ({last_metrics['date']}):")
        print(f"- Resting HR : {last_metrics['rhr']} bpm")
        print(f"- Overnight HRV: {last_metrics['hrv']} ms")
        print(f"- Sleep Score: {last_metrics['sleep_score']}")
        print(f"- Stress     : {last_metrics['stress']}")
        print(f"- ACWR       : {last_metrics['acwr']:.2f} (Acute: {last_metrics['acute_workload']:.1f}, Chronic: {last_metrics['chronic_workload']:.1f})")
        
        # Baselines
        baseline = db.get_baseline(last_metrics['date'])
        if baseline:
            print(f"Baselines (28-day):")
            print(f"- RHR Mean   : {baseline['rhr_baseline_mean']:.1f} (std: {baseline['rhr_baseline_std']:.2f})")
            print(f"- HRV Mean   : {baseline['hrv_baseline_mean']:.1f} (std: {baseline['hrv_baseline_std']:.2f})")
            print(f"- Sleep Mean : {baseline['sleep_baseline_mean']:.1f} (std: {baseline['sleep_baseline_std']:.2f})")
    else:
        print("\nRecent Garmin Metrics: No cached metrics. Run 'sync-sheets' first.")

    # Coach Memory
    strategy = db.get_coach_memory("training_strategy")
    learnings = db.get_coach_memory("athlete_learnings")
    print(f"\nCoach Memory:")
    print(f"- Strategy  : {strategy or 'Not established'}")
    print(f"- Learnings : {learnings or 'None yet'}")
    print("\n================================")

def run_plan():
    # Make sure we have latest metrics cached
    metrics = db.get_metrics_cache()
    if not metrics:
        print("Warning: Metrics cache is empty. Fetching from Google Sheets first...")
        sheets_reader.sync_data()
        
    try:
        reasoning, workouts = coach_engine.replan()
        print("\n=== PLAN GENERATED BY COACH ===")
        print(f"Reasoning:\n{reasoning}\n")
        print(f"Generated {len(workouts)} workouts starting from today. Save complete.")
        print("Run 'sync' to commit this plan to Google Calendar.")
    except Exception as e:
        print(f"Error during plan generation: {e}")

def run_adapt(args):
    # Optional date argument
    parser = argparse.ArgumentParser(description="Run daily metrics adaptation")
    parser.add_argument("--date", help="Date in YYYY-MM-DD format (defaults to UTC today)")
    parsed = parser.parse_args(args)
    
    date_str = parsed.date or datetime.now(timezone.utc).strftime("%Y-%m-%d")
    print(f"Evaluating daily Garmin metrics adaptation for {date_str}...")
    
    try:
        reason, adapted_workout = coach_engine.daily_adapt(date_str)
        print(f"\nDecision Summary:\n{reason}")
        if adapted_workout:
            print(f"\nAdapted Workout Synced to Calendar: {adapted_workout['title']}")
    except Exception as e:
        print(f"Error executing daily adaptation: {e}")

def run_sync():
    today_str = datetime.now(timezone.utc).strftime("%Y-%m-%d")
    planned_workouts = db.get_workouts(start_date=today_str)
    # Filter to only unsynced/planned ones
    unsynced = [w for w in planned_workouts if w['status'] in ('planned', 'modified')]
    
    if not unsynced:
        print("No new or modified workouts to sync. Run 'plan' to generate a schedule.")
        return
        
    print(f"Syncing {len(unsynced)} workouts to Google Calendar...")
    try:
        calendar_syncer.sync_multiple(unsynced)
        print("Google Calendar synchronization completed.")
    except Exception as e:
        print(f"Error syncing to Google Calendar: {e}")

def run_sync_sheets():
    try:
        sheets_reader.sync_data()
    except Exception as e:
        print(f"Error syncing Google Sheets: {e}")

def run_add_goal(args):
    parser = argparse.ArgumentParser(description="Add active training goal")
    parser.add_argument("--title", required=True, help="Goal title (e.g. Marathon)")
    parser.add_argument("--date", required=True, help="Target event date (YYYY-MM-DD)")
    parser.add_argument("--sport", required=True, choices=["running", "road_biking", "hiking", "strength_training"], help="Sport type")
    parser.add_argument("--desc", default="", help="Description")
    parser.add_argument("--priority", type=int, default=1, help="Goal priority (1 = highest)")
    parsed = parser.parse_args(args)
    
    db.add_objective(
        title=parsed.title,
        target_date=parsed.date,
        sport_type=parsed.sport,
        description=parsed.desc,
        priority=parsed.priority,
        status='active'
    )
    print(f"Goal '{parsed.title}' added successfully. Run 'plan' to generate training cycles.")

def run_add_event(args):
    parser = argparse.ArgumentParser(description="Add major life event")
    parser.add_argument("--title", required=True, help="Event title (e.g. Vacation to Spain)")
    parser.add_argument("--start", required=True, help="Start date (YYYY-MM-DD)")
    parser.add_argument("--end", required=True, help="End date (YYYY-MM-DD)")
    parser.add_argument("--type", required=True, choices=["injury", "vacation", "party", "other"], help="Event type")
    parser.add_argument("--desc", default="", help="Description/Impact description")
    parsed = parser.parse_args(args)
    
    db.add_life_event(
        title=parsed.title,
        start_date=parsed.start,
        end_date=parsed.end,
        event_type=parsed.type,
        impact_description=parsed.desc
    )
    print(f"Life event '{parsed.title}' logged. This will be factored in when running 'plan' or 'adapt'.")

def run_list_goals():
    goals = db.get_objectives()
    print("=== TRAINING OBJECTIVES / GOALS ===")
    for g in goals:
        print(f"[{g['status'].upper()}] ID: {g['id']} | {g['title']} ({g['sport_type']}) on {g['target_date']} (Priority: {g['priority']})")
        if g.get('description'):
            print(f"  Description: {g['description']}")

def run_list_events():
    events = db.get_life_events()
    print("=== ATHLETE LIFE EVENTS ===")
    for e in events:
        print(f"ID: {e['id']} | {e['title']} ({e['event_type']}): {e['start_date']} to {e['end_date']}")
        if e.get('impact_description'):
            print(f"  Impact: {e['impact_description']}")

def run_list_workouts():
    workouts = db.get_workouts()
    print("=== WORKOUT SCHEDULE ===")
    for w in workouts:
        mod_marker = " [ADAPTED]" if w['status'] == 'modified' or w['modification_reason'] else ""
        sync_marker = " [SYNCED]" if w['status'] == 'synced' else ""
        print(f"{w['date']} | {w['sport_type'].upper()} | {w['title']}{mod_marker}{sync_marker}")
        print(f"  Description: {w['description']}")
        if w.get('modification_reason'):
            print(f"  Reason: {w['modification_reason']}")
        print("-" * 40)

if __name__ == "__main__":
    main()
