import os
import unittest
from datetime import datetime, timedelta, timezone
from unittest.mock import patch

from tests.helpers import clear_all_tables, run_cli

TEST_DB_PATH = os.path.join(os.path.dirname(__file__), "test_trainmate_cli_plans.db")

from trainmate.db import Database
import trainmate.db
import trainmate_cli

test_db = Database(db_path=TEST_DB_PATH)
trainmate.db.db = test_db
trainmate_cli.db = test_db


class TestCliPlans(unittest.TestCase):
    @classmethod
    def setUpClass(cls):
        if os.path.exists(TEST_DB_PATH):
            os.remove(TEST_DB_PATH)
        global test_db
        test_db = Database(db_path=TEST_DB_PATH)
        trainmate.db.db = test_db
        trainmate_cli.db = test_db

    @classmethod
    def tearDownClass(cls):
        if os.path.exists(TEST_DB_PATH):
            try:
                os.remove(TEST_DB_PATH)
            except OSError:
                pass

    def setUp(self):
        clear_all_tables(test_db)

    def run_cli(self, args, input_value="n"):
        return run_cli(args, input_value)

    @patch("trainmate_cli.garmin")
    @patch("trainmate_cli.coach_service")
    def test_plan_commands(self, mock_coach, mock_garmin):
        mock_coach.plan_generate.return_value = (
            "Mock Strategy",
            [{"name": "Meso 1", "start_date": "2026-01-01", "end_date": "2026-01-28", "focus": "Base"}],
            False
        )
        mock_coach.workout_generate.return_value = (
            "Test workout reasoning",
            [{"title": "Test Workout"}],
        )

        exit_code, stdout, stderr = self.run_cli(["plan", "generate"])
        self.assertEqual(exit_code, 0)
        self.assertIn("Plan discarded", stdout)
        mock_coach.plan_generate.assert_called_once_with(force=False, auto_apply=False)

        mock_coach.plan_generate.reset_mock()
        exit_code, stdout, stderr = self.run_cli(["plan", "generate", "-f"])
        self.assertEqual(exit_code, 0)
        mock_coach.plan_generate.assert_called_once_with(force=True, auto_apply=False)

        mock_coach.plan_generate.reset_mock()
        exit_code, stdout, stderr = self.run_cli(["plan", "generate", "--force"])
        self.assertEqual(exit_code, 0)
        mock_coach.plan_generate.assert_called_once_with(force=True, auto_apply=False)

        exit_code, stdout, stderr = self.run_cli(["workout", "generate"])
        self.assertEqual(exit_code, 0)
        self.assertIn("=== WORKOUTS GENERATED BY COACH ===", stdout)
        self.assertIn("Test workout reasoning", stdout)
        mock_coach.workout_generate.assert_called_once()

        exit_code, stdout, stderr = self.run_cli(["plan", "show"])
        self.assertEqual(exit_code, 0)
        self.assertIn("No active goals found", stdout)

        obj_id = test_db.add_objective(
            title="London Marathon",
            target_date="2026-09-20",
            sport_type="running",
            priority=1,
        )

        exit_code, stdout, stderr = self.run_cli(["plan", "show"])
        self.assertEqual(exit_code, 0)
        self.assertIn("No active macrocycle strategy found", stdout)

        test_db.save_macrocycle(
            objective_id=obj_id,
            strategy="Build base then taper",
            goals_hash="ghash",
            constraints_hash="chash",
            mesocycles=[{
                "name": "Base Building",
                "start_date": "2026-06-01",
                "end_date": "2026-06-28",
                "focus": "Aerobic threshold volume",
            }],
        )

        exit_code, stdout, stderr = self.run_cli(["plan", "show"])
        self.assertEqual(exit_code, 0)
        self.assertIn("=== ACTIVE MACROCYCLE STRATEGY ===", stdout)
        self.assertIn("Build base then taper", stdout)
        self.assertIn("Base Building", stdout)

        mock_coach.plan_rm.reset_mock()
        obj_to_rm = test_db.add_objective(
            title="Goal to remove plan for",
            target_date="2026-09-22",
            sport_type="running",
        )
        test_db.save_macrocycle(
            objective_id=obj_to_rm,
            strategy="Plan to delete",
            goals_hash="ghash",
            constraints_hash="lhash",
            mesocycles=[],
        )
        exit_code, stdout, stderr = self.run_cli(["plan", "rm", str(obj_to_rm)])
        self.assertEqual(exit_code, 0)
        self.assertIn("removed successfully", stdout)
        mock_coach.plan_rm.assert_called_once_with(obj_to_rm)

    @patch("trainmate_cli.garmin")
    def test_plan_show_never_pulls(self, mock_garmin):
        # `plan show` is a pure read: it must never prompt or trigger a Garmin pull,
        # whether or not metrics exist (auto-ensure lives on the generating/adapting
        # commands, not on read-only views).
        test_db.save_metric_cache(
            date="2026-06-03", rhr=50, hrv=75, sleep_score=80, stress=20
        )
        with patch("builtins.input") as mock_input:
            exit_code, stdout, stderr = self.run_cli(["plan", "show"])
            self.assertEqual(exit_code, 0)
            mock_input.assert_not_called()
            mock_garmin.pull.assert_not_called()
            mock_garmin.ensure_data.assert_not_called()

        with test_db._get_connection() as conn:
            conn.execute("DELETE FROM athlete_metrics_cache")
            conn.commit()

        exit_code, stdout, stderr = self.run_cli(["plan", "show"])
        self.assertEqual(exit_code, 0)
        mock_garmin.pull.assert_not_called()

    def test_plan_versions_and_show_version(self):
        """`plan versions` lists active + superseded versions; `plan show --version`
        renders a specific superseded version (see DESIGN_plan_rollback.md)."""
        oid = test_db.add_objective(
            title="Versioned Goal", target_date="2026-12-15",
            sport_type="running", priority=1,
        )
        meso = [{
            "name": "Base", "start_date": "2026-06-01",
            "end_date": "2026-06-28", "focus": "Base",
        }]
        v1 = test_db.save_macrocycle(
            objective_id=oid, strategy="First strategy alpha",
            goals_hash="g", constraints_hash="l", mesocycles=meso,
        )
        v2 = test_db.save_macrocycle(
            objective_id=oid, strategy="Second strategy beta",
            goals_hash="g", constraints_hash="l", mesocycles=meso,
        )

        exit_code, stdout, _ = self.run_cli(["plan", "versions"])
        self.assertEqual(exit_code, 0)
        self.assertIn(f"ID {v1}", stdout)
        self.assertIn(f"ID {v2}", stdout)
        self.assertIn("active", stdout)
        self.assertIn("superseded", stdout)

        # Showing the superseded version renders its strategy under a superseded header.
        exit_code, stdout, _ = self.run_cli(["plan", "show", "--version", str(v1)])
        self.assertEqual(exit_code, 0)
        self.assertIn("SUPERSEDED", stdout)
        self.assertIn("First strategy alpha", stdout)

        # A version id from another goal is rejected.
        other = test_db.add_objective(
            title="Other Goal", target_date="2027-01-15",
            sport_type="running", priority=1,
        )
        exit_code, stdout, _ = self.run_cli(
            ["plan", "show", "--goal", str(other), "--version", str(v1)]
        )
        self.assertIn("does not belong", stdout)
